-- ============================================================
-- Tabel FAQ (bisa diedit dari /admin/faq).
-- Jalankan di Supabase -> SQL Editor. Aman dijalankan ulang.
-- ============================================================
create table if not exists public.faqs (
  id bigint generated by default as identity primary key,
  question text not null,
  answer text not null,
  order_index int not null default 0,
  created_at timestamptz not null default now()
);

alter table public.faqs enable row level security;

drop policy if exists "faqs public read" on public.faqs;
create policy "faqs public read" on public.faqs for select using (true);

-- Contoh awal (hanya jika tabel masih kosong)
insert into public.faqs (question, answer, order_index)
select * from (values
  ('Layanan apa saja yang Invisual tawarkan?',
   'Kami fokus pada brand identity, ilustrasi, desain kemasan, dan desain visual lainnya untuk membantu brand tampil menonjol dan punya karakter.', 0),
  ('Berapa lama pengerjaan sebuah proyek?',
   'Bergantung pada ruang lingkup, umumnya 2–6 minggu. Kami akan memberi estimasi waktu yang jelas di awal.', 1),
  ('Bagaimana proses kerja samanya?',
   'Dimulai dari diskusi kebutuhan, penawaran, riset, konsep, revisi, hingga finalisasi dan serah terima aset.', 2),
  ('Berapa biaya sebuah proyek branding?',
   'Biaya menyesuaikan kebutuhan dan skala proyek. Silakan hubungi kami melalui halaman Kontak untuk penawaran.', 3),
  ('Apakah bisa mengerjakan proyek jarak jauh?',
   'Bisa. Kami terbiasa bekerja dengan klien dari berbagai lokasi secara daring.', 4)
) as v(question, answer, order_index)
where not exists (select 1 from public.faqs);
